### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nellsavedra** [gabrielcarloto/flow-search-mdn#5]
Hey Gabriel, nice plugin thank you!, ¿is there any option to set the plugin to open the url in a different browser than the default one?, it's a weird question i know, but i have chrome for work stuff, firefox for personal stuff and firefox dev for work development, i really would like to config that mdn always open in firefox dev

**Comment by nellsavedra** [comment]
Just saw you made it in ts, i can add the browser to open() function, thanks again for the plugin!

**Comment by gabrielcarloto** [comment]
Hey, thanks! This would be a nice feature. Don't know about the implementation, though. I could add some browsers in the plugin settings, but if someone selects a browser they don't have installed it would lead to an error I think. Maybe there is a way to get a list of the installed browsers, but I did not find one (at least not for Windows 10 or 11).
